export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING"; 
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"; 
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
export const IN_PROGRESS_PERSONAL_COUNT = "IN_PROGRESS_PERSONAL_COUNT";
export const TODO_PERSONAL_COUNT = "TODO_PERSONAL_COUNT";
export const DONE_PERSONAL_COUNT = "DONE_PERSONAL_COUNT";
export const TODODATA = "TODODATA"
export const INPROGRESSDATA = "INPROGRESSDATA"
export const DONEDATA = "DONEDATA"



